export const WORKOUT_SAVE_FAIL = 'WORKOUT_SAVE_FAIL';
export const WORKOUT_SAVE_SUCCESS = 'WORKOUT_SAVE_SUCCESS';
export const WORKOUT_SAVE_REQUEST = 'WORKOUT_SAVE_REQUEST';

export const WORKOUT_DELETE_FAIL = 'WORKOUT_DELETE_FAIL';
export const WORKOUT_DELETE_SUCCESS = 'WORKOUT_DELETE_SUCCESS';
export const WORKOUT_DELETE_REQUEST = 'WORKOUT_DELETE_REQUEST';
