export const WORKOUT_SAVE_FAIL = 'WORKOUT_SAVE_FAIL';
export const WORKOUT_SAVE_SUCCESS = 'WORKOUT_SAVE_SUCCESS';
export const WORKOUT_SAVE_REQUEST = 'WORKOUT_SAVE_REQUEST';

export const WORKOUT_DELETE_FAIL = 'WORKOUT_DELETE_FAIL';
export const WORKOUT_DELETE_SUCCESS = 'WORKOUT_DELETE_SUCCESS';
export const WORKOUT_DELETE_REQUEST = 'WORKOUT_DELETE_REQUEST';

export const WORKOUT_LIST_REQUEST = 'WORKOUT_LIST_REQUEST';
export const WORKOUT_LIST_FAIL = 'WORKOUT_LIST_FAIL';
export const WORKOUT_LIST_SUCCESS = 'WORKOUT_LIST_SUCCESS';

export const WORKOUT_PERSONAL_LIST_REQUEST = 'WORKOUT_PERSONAL_LIST_REQUEST';
export const WORKOUT_PERSONAL_LIST_FAIL = 'WORKOUT_PERSONAL_LIST_FAIL';
export const WORKOUT_PERSONAL_LIST_SUCCESS = 'WORKOUT_PERSONAL_LIST_SUCCESS';
